<a href="https://colab.research.google.com/github/Alekhyo/Numpy/blob/master/Fancy%20Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
arr1=np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
# Q1 Write a numpy code to swap col1([0,5,10,15]) with col4([3,8,13,18])

In [0]:
arr1[:,[0,3]]=arr1[:,[3,0]]
arr1

array([[ 3,  1,  2,  0,  4],
       [ 8,  6,  7,  5,  9],
       [13, 11, 12, 10, 14],
       [18, 16, 17, 15, 19]])

In [0]:
# Q2 Write a numpy code to reverse the rows of arr1
# The output should be [15, 16, 17, 18, 19] as first row and [ 0,  1,  2,  3,  4] as last row

In [0]:
arr1=np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
arr1=arr1[::-1]
arr1

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [0]:
# Q3 Write a code to replace all the nan(missing values) of arr2 with the mean of arr2

In [0]:
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr2

array([[ 1.,  2., nan],
       [ 4.,  5.,  6.],
       [nan, nan,  9.]])

In [0]:
arr2[np.isnan(arr2)]=np.nanmean(arr2)
arr2

array([[1. , 2. , 4.5],
       [4. , 5. , 6. ],
       [4.5, 4.5, 9. ]])

In [0]:
# Q4 Write a code which can fetch all items from arr3 which are either greater than 25 or a multiple of 3

In [0]:
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr3

array([[54, 60, 53, 27],
       [82, 75, 67, 26],
       [17, 50, 87, 83],
       [51, 41, 48,  6],
       [54, 29,  4, 14]])

In [0]:
arr3[(arr3>25) | (arr3%3==0)]

array([54, 60, 53, 27, 82, 75, 67, 26, 50, 87, 83, 51, 41, 48,  6, 54, 29])

In [0]:
# Q5 Write a code to find the 10th, 25th, 50th(median) percentile of arr3


In [0]:
import math
def percentile(arr,n):
       arr=np.sort(arr,axis=None)
       pos=((n/100)*len(arr))
       if (pos).is_integer()==True:
         pos=int(pos)
         return((arr[pos-1]+arr[pos])/2)
       else:
         pos=math.ceil(pos)
         return(arr[pos-1])


In [0]:
val=percentile(arr3,10)
val

10.0

In [0]:
np.percentile(arr3,10)

13.200000000000001

In [0]:
val1=percentile(arr3,25)
val1

26.5

In [0]:
np.percentile(arr3,25)

26.75

In [0]:
val2=percentile(arr3,50)
val2

50.5

In [0]:
np.percentile(arr3,50)

50.5