<a href="https://colab.research.google.com/github/Alekhyo/Numpy/blob/master/Indexing%20in%20Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [2]:
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [0]:
# Q1. From arr1 you have to fetch out every alternate column starting from col1

In [0]:
arr1[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23],
       [26, 28],
       [31, 33],
       [36, 38]])

In [0]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 

In [0]:
arr1[::3,::2]

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [0]:
# Setup for question
# Generating a random numpy array of intergers ranging between 1 and 1000

arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[6749, 2326, 9506, 4980, 4126],
		       [3833, 1653, 4874, 9166,  297]])

 **Normalization** rescales the values into a range of [0,1]. This might be useful in some cases where all parameters need to have the same positive scale. You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). The formula for normalization is given below

 Xchanged=(X−Xmin)/(Xmax−Xmin)

In [0]:
# Q3. Write a code to normalize arr2.

In [0]:
arr2=np.array([[6749, 2326, 9506, 4980, 4126],[3833, 1653, 4874, 9166,  297]])

In [0]:
xmax,xmin=arr2.max(),arr2.min()

In [0]:
arr2=(arr2-xmin)/(xmax-xmin)

In [0]:
arr2

array([[0.70061896, 0.22032794, 1.        , 0.50852427, 0.4157889 ],
       [0.3839722 , 0.14724726, 0.49701379, 0.9630796 , 0.        ]])

In [0]:
# Q4. How would you check if your numpy array has some missing values?

In [0]:
import numpy as np

In [0]:
arr1=np.array([1, np.nan, 2, 3])      # nan is used insted of missing values 

In [0]:
np.nansum(arr1)

6.0

In [0]:
np.nanmean(arr1)

2.0

In [0]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

In [0]:
import numpy as np

In [0]:
def nth_largest(array,n):

    """
              This function prints the nth largest element of an 1D NumPy array
              Date:08/02/2020
              Created By:Alekhyo
              Input:1D numpy array,an integer
              Output:an integer
    """
    array=np.unique(array)                                     #removes duplicate elements
    
    if n>0 and n<=len(array):
      array=np.sort(array)
      print("The {} largest element is {}".format(n,array[-n]))
    
    else:
      print("invalid arguments \nFirst argument takes a 1D array  \nSecond argument takes integer 0<n<=length_of_array_passed")



In [6]:
nth_largest([40,1,3,10,5,20,30],0)


invalid arguments 
First argument takes a 1D array  
Second argument takes integer 0<n<=length_of_array passed


In [8]:
nth_largest([40,1,3,10,5,20,30],8)


invalid arguments 
First argument takes a 1D array  
Second argument takes integer 0<n<=length_of_array_passed


In [9]:
nth_largest([40,1,3,10,5,20,30,30],3)


The 3 largest element is 20
